server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/GMS2026
    username: "postgres"
    password: "admin"
    hikari:
      pool-name: data
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000

logging:
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
  level:
    root: INFO
    com.app.backend: INFO